# -*- coding: utf-8 -*-
"""Number Guessing Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNRGL09baYGJPvcywdoAtp7w8smHtofk
"""

import random # The Random is a Library Where it takes the random call from a range example if we take randint it takes random integer from given range
# Syntax is: random.randint(from,to)

print("!Welcome to The Number Guessing Game!")
print("The Rules of this game are: ")
print("     -> Computer picks one random number from 1 to 100")
print("     -> You have difficulty based Atteempts To Guess The Number ")
print("Difficulty Levels are:  Easy, Medium and Hard")
print("No.of Choice for Each Level are: ")
print(" EASY--> 5")
print(" MEDIUM--> 3")
print(" HARD--> 1")
print("   <---------------------------So Let's Begin---------------------------->   ")
computerScore=0
userscore=0
while(True):
  flag=0
  print("!Computer Picking a Number!")
  computer=random.randint(1,100)
  dl=input("Enter Difficulty Level: 'E' for Easy 'M' For Medium 'H' For Hard: ")
  if dl.lower()=='e':
    attempts=5
  elif dl.lower()=='m':
    attempts=3
  else:
    attempts=1
  print("Computer Picked The Number-----> ")
  while(attempts):
    user=int(input("    ----> Enter Your Number: "))
    if user>100 or user<1:
      print("Enter Correct Number from 1 to 100 only!")
      flag=1
      break
    if(user==computer):
      print("Congratulations! You Guess The Correct Number")
      print("You Won")
      userscore+=1
      break
    elif user!=computer:
      if user>computer:
        print("You are Too High! Please Try Again: ")
      elif user<computer:
        print("You are Too Low! Please Try Again: ")
    attempts-=1
  if attempts==0:
    print(f"You Lost The Game! The computer picked Number is {computer}")
    computerScore+=1
  elif flag==1:
    print("You Entered a number out of bounds so this game is skipped")
  print("-------------------------------------------------------------------------------")
  print("Do you Want to Continue if yes then type 'Y' no then type 'N' ")
  b=input("Enter your choice: Y or N -->")
  if b.lower()=='n':
    break
print("---------------------------------------------------------------------------------")
print("                               FINAL SCORECARD                                   ")
print("---------------------------------------------------------------------------------")
print(f"           Computer Score =  {computerScore}")
print(f"           User Score     =  {userscore}")
print("---------------------------------------------------------------------------------")
print("                         !Game Ends Thanks For Playing!                          ")
print("---------------------------------------------------------------------------------")